### Setup Notebook

In [7]:
import os
import re

import json
import pandas as pd
from tqdm.auto import tqdm

from openai import OpenAI

In [8]:
LLM_MODEL = 'gemma2:2b'

### Utility Functions

In [9]:
def export_df_to_json(df, filename):
    '''
    df : the dataframe that needs to be dumped as json
    filename : string path and name of the destination json file
    '''
    df_json = df.to_dict(orient="records")
    with open(filename, 'wt') as f_out:
        json.dump(df_json, f_out, indent=2)



def load_jsonfile(filename):
    '''
    filename : filepath and filename(.json file) as a single string
    This function can be used to read any json file
    '''
    with open(filename, 'rt') as f:
        data_json = json.load(f)
    return data_json

In [10]:
def find_symbol_positions(input_string):

    positions = {'[': [], ']': [], '"': [], "'": [], '-': [], '?': []}

    for symbol in positions.keys():
        # find all matches of the current symbol in the input string
        matches = [match.start() for match in re.finditer(re.escape(symbol), input_string)]
        positions[symbol] = matches

    return positions



def extract_query5(input_string, positions):
    if (len(positions['['])==0) or (len(positions[']'])==0):
        # if not within box brackets, queries might be between '-' and '?'
        quoted_strings = []
        j = 0
        for dash in positions['-']:
            while j < len(positions['?']) and positions['?'][j] <= dash:
                j+=1
            if j < len(positions['?']):
                quoted_strings.append(input_string[dash+1 : positions['?'][j]+1].replace('*','').strip())
        return quoted_strings
    
    start_bracket = positions['['][0]
    end_bracket = next((pos for pos in positions[']'] if pos > start_bracket), None)

    if end_bracket is None:
        return []
    
    quoted_strings = []
    quote_positions = [pos for pos in positions['"'] if start_bracket < pos < end_bracket]
    single_quotes = positions["'"]

    for i in range(0, len(quote_positions) - 1, 2):
        start_quote = quote_positions[i]
        end_quote = quote_positions[i + 1]
        for sq in single_quotes:
            if start_quote < sq < end_quote:
                single_quotes.remove(sq)
        # extract the string between quotes and add it to the list
        quoted_strings.append(input_string[start_quote + 1:end_quote].replace('*','').strip())
    
    if (quoted_strings==[]) and (len(positions['?']) > 0) and (len(single_quotes) > 0):
        # searching for queries be between "'" and '?'
        j = 0
        for squote in positions['-']:
            while j < len(single_quotes) and positions['?'][j] <= squote:
                j+=1
            if j < len(positions['?']):
                quoted_strings.append(input_string[squote+1 : positions['?'][j]+1].replace('*','').strip())

    return quoted_strings

In [11]:
def llm(prompt, llm_model='gemma2:2b'):
    '''
    This function uses 'llm_model' to generate response for the provided input 'prompt' to llm.
    '''
    client = OpenAI(
    base_url='http://localhost:11434/v1/',
    api_key='ollama',
    )
    
    response = client.chat.completions.create(
        model=llm_model,
        messages=[{"role": "user", "content": prompt}],
        # temperature=0,    # remove randomness for deterministic output but not using it as it makes summary clumsy with phrases like 'you stated correctly...', 'you explained it well...' etc.
        seed=72
    )

    return response.choices[0].message.content

In [12]:
def generate_questions(tscript_chunk, llm_model='gemma2:2b'):
    '''
    This function takes in a 'transcript' text and generates summarized text using 'llm_model' specified.
    '''
    querygen_prompt = """You emulate a student who is learning from youtube videos.
        Formulate 5 questions this user might ask based on a provided video transcript, cleaned and summarized texts and its keywords.
        Make the questions specific to this transcript.
        The record should contain the answer to the questions, and the questions should be complete and not too short.
        Use as fewer words as possible from the record.

        The record:

        original_transcript: {text}
        summary_text: {smry_text}
        cleaned_text: {clean_text}
        keywords: {keywords}

        Provide the output in a python list without using code blocks:

        ["question1", "question2", ..., "question5"]
        """.strip()

    prompt = querygen_prompt.format(**tscript_chunk)

    return llm(prompt, llm_model)

In [13]:
def generate_query_file(documents, llm_model='gemma2:2b', retry=3, debug=0):
    '''
    Iterates through each row and generates 5 possible queries a viewer/student could ask.
    since LLMs are unreliable, we try 'retry' number of times to generate queries before passing on to next chunk.
    Returns a dataframe with query column and uid to identify the ground truth chunk.
    '''
    print(f"INFO: initiated query generation")
    print(f"INFO: total text chunks {len(documents)}")
    
    groundtruth = []
    success=0
    failure=0

    for doc in tqdm(documents, total=len(documents), desc="Generating Queries"):
        attempt=1
        query5=[]

        while(query5==[] and attempt<=retry):
            llm_response = generate_questions(doc, llm_model)
            positions = find_symbol_positions(llm_response)
            query5 = extract_query5(llm_response, positions)
            attempt+=1

        for query in query5:
            temp = {'uid': doc['uid'], 'query':query}
            groundtruth.append(temp)
            if debug:
                print(f"Query: {query}\n")
        
        if query5==[]:
            failure+=1
        else:
            success+=1
    
    df_query5 = pd.DataFrame(groundtruth)

    print(f"INFO: query generation finished")
    print(f"INFO: total documents - {len(documents)} | success - {success} | failure - {failure}")
    return df_query5

### Import Chunked Transcribe Data

In [14]:
tscribe_data_loc = "../app/app_data/multi_tscribe.json"
tscribe_data = pd.read_json(tscribe_data_loc)
tscribe_data['video_id'] = tscribe_data['uid'].apply(lambda x: x.split('__B')[0])
tscribe_data.head(3)

,uid,text,smry_text,clean_text,keywords,video_id
0,t6Wc7OMks4U__B1__S0.0,"Every piece of art tells a story. Usually, mo...","Biombo: A Folding Screen \nJapanese design, d...","Every piece of art tells a story. Usually, mor...","creative process, art history, biographies, \n...",t6Wc7OMks4U
1,t6Wc7OMks4U__B2__S61.88,"you look at, and who’s doing the telling. By ...",### Crash Course Art History: Unveiling art's ...,"""You look at and who’s telling it. By studying...","sart history, art appreciation, object studyin...",t6Wc7OMks4U
2,t6Wc7OMks4U__B3__S121.84,but also reveals the ideas that \nconnect peo...,This transcript explores the history of Art Hi...,And also reveals ideas that connect people acr...,"Keyword1: Art History, #Keyword 2: Renaissance...",t6Wc7OMks4U

In [15]:
tscribe_data.shape, tscribe_data['video_id'].unique()

((196, 6),
 array(['t6Wc7OMks4U', 'zjkBMFhNj_g', '1A_CAkYt3GY', 'NKEhdsnKKHs',
        'AUXIuYHFgBE', 'YQcuTYcxxWc', '-wrCpLJ1XAw', 'IV-8YsyghbU',
        'MLKrmw906TM', '5C-s4JrymKM', 'kXhJ3hHK9hQ', '-X8Xfl0JdTQ',
        'FmTsS5xFA6k', 'TgisehuGOyY', '7e9v_fsZB6A', 'gs_gY1K1AMU',
        '9AzNEG1GB-k', 'AYkhlXronNk', 'S93jMOqF-oE', 'YaDvRdLMkHs',
        'mjQwedC1WzI', '-TFCMK4i2lo', 'trqDnLNRuSc', '17WiQ_tNld4'],
       dtype=object))

In [16]:
documents = load_jsonfile("../app/app_data/multi_tscribe.json")

len(documents), documents[0]

(196,
 {'uid': 't6Wc7OMks4U__B1__S0.0',
  'text': " Every piece of art tells a story. Usually, more than one. I’ll show you. This is a biombo, a folding screen made in Mexico\xa0\nand inspired by Japanese decorative designs. It existed before we had pianos\xa0\nor bicycles or even sandwiches. This one would have decorated a wealthy Spaniard’s\xa0\nhome in late seventeenth-century Mexico. And while it might look like mere decoration,\xa0\nif you lean in, it'll tell you a story. A story of a battle, where Spain conquered\xa0\nTenochtitlan, or modern day Mexico City,\xa0\xa0 and the Aztec emperor Moctezuma the Second\xa0\nwas killed by one of his own subjects. But records from the Indigenous people of\xa0\nMexico tell a different story of the same event. In their account, the Spanish killed the\xa0\nAztec emperor, as part of their conquest. Historical events like this — and history\xa0\nitself — aren’t exactly straightforward. The story you get varies, depending\xa0\non which documents, or artworks,\xa0\xa0 you look at, and who’s doing the telling. By studying this centuries-old screen we\xa0\nlearn about more than just the object itself. We learn about history — and how history,\xa0\xa0 like art, is not something we\xa0\ndiscover, but something we create. Hi! I'm Sarah Urist Green. I’m a curator and art educator, and\xa0\nthis is Crash Course Art History. You might think that art history\xa0\nis a stuffy subject that’s only\xa0\xa0 useful for clinching a trivia night victory. Or you might think it’s just\xa0\nmemorizing a bunch of names and dates,\xa0\xa0 with the occasional jump-scare\xa0\nfrom a creepy, long-limbed baby. But art history is really about thinking\xa0\ncritically by observing closely. It’s the study of objects and\xa0\nimages to understand the people,\xa0\xa0 places and time periods they come from. Art reflects different perspectives and stories\xa0\xa0 but also reveals the ideas that\xa0\nconnect people across the world. And that three-letter word —\xa0\n“art” — holds some big ideas. It can include ancient cave paintings and pride\xa0\nflags, state-funded monuments and street art,\xa0\xa0 works designed for function and\xa0\nworks designed to ruffle feathers. And since art is subjective, what’s\xa0\na beautiful sculpture to one person,\xa0\xa0 might be the stuff of nightmares to another. Plus, ideas about what art is have\xa0\nchanged—and continue to change—over time. Not all cultures think of art the same way, or\xa0\neven have a word for “art” in their language. Like, the Lega people from what’s now\xa0\nthe Democratic Republic of the Congo\xa0\xa0 have a category of objects called\xa0\nmasengo, which roughly translates\xa0\xa0 to “heavy things” and refers to items\xa0\nwith great significance or “weight.” As for you, when you hear “art history,”\xa0\nyou might think of something like this. Whoops, sorry, I meant, this: The\xa0\nwell-known Sistine Chapel ceiling,\xa0\xa0 painted by Michelangelo di\xa0\nLodovico Buonarroti Simoni. No clue why we call him by his first name. But let’s explore why that ceiling\xa0\ncomes to mind when you think about art,\xa0\xa0 and why you’ve heard of the guy who painted it. Let’s go to the drawing board! The story of the Sistine Chapel doesn’t\xa0\nactually begin with Michelangelo,\xa0\xa0 but with a wealthy Italian\xa0\nfamily called the Medicis. The Medicis ruled Florence and, later,\xa0\nTuscany, from the 15th to the 18th centuries. They also controlled the what, where,\xa0\nand how of the local art scene. They financially supported several\xa0\nhuge artists—including Michelangelo. So with the Medici Brand behind him, Michelangelo\xa0\nwas basically one of Italy’s biggest influencers. He even caught the eye of Pope Julius\xa0\nthe Second, who commissioned him to\xa0\xa0 paint the now famous Sistine Chapel ceiling. Now, the Medicis were also sponsors of the\xa0\npainter and architect Giorgio Vasari, who\xa0\xa0 wrote a book called “Lives of the Most Excellent\xa0\nItalian Painters, Sculptors, and Architects.” It celebrated Michelangelo\xa0\nand other artists like him,\xa0\xa0 and it gave the Medicis credit for\xa0\nsupporting a historic, quote, “rebirth.” In fact, before the French term “Renaissance”\xa0\nbecame prominent in the 19th century,\xa0\xa0 Vasari described this artistic moment in time as\xa0\n“rinascita”— Italian for “renewal” or “rebirth.” So yeah, the book was basically\xa0\nsixteenth-century sponsored content,\xa0\xa0 and it became the bedrock of\xa0\nwhat we know now as art history. It shaped not only the way\xa0\nart history would be written,\xa0\xa0 but which artworks were considered important,\xa0\ntalked about, and eventually meme-ified. Of course, writing about art\xa0\ndidn’t start with Vasari. By the fifth and fourth centuries B.C.E.,\xa0\nPlato was wrestling with art’s imitation\xa0\xa0 of reality in his writings, and Aristotle\xa0\nwas exploring how art can conjure emotions. And in the ninth century, Zhang Yanyuan\xa0\nwrote “Famous Paintings of Successive\xa0\xa0",
  'smry_text': 'Biombo: A Folding Screen  \nJapanese design, dating back centuries, this biombo tells a story through its decorative elements. The screen\'s rich history is evident; it served as decor in a wealthy Spanish home during the late 17th century.\n\nThe Biombo as Symbol\nHistorical events like Spanish conquest of Tenochtitlan are often presented differently based on the primary source, artwork, or document examined.  Native accounts and records offer differing stories, highlighting the complexity of historical documentation. Learning about this biombo helps us understand the multifaceted nature of history itself. \n\nThe Craft of Interpreting the Past\nThis video explores art in connection with history, examining objects like the biombo as a tool to learn about different perspectives and narratives. Art represents cultural influences, ideas, and individual experiences. The discussion also expands on how art\'s interpretation varies across cultures, referencing indigenous classifications from modern Congo tribes.\n\nThe Subjectivity of Art\nArt holds power through varied mediums—from ancient cave paintings to modern-day works. Art can evoke feelings, ignite inspiration, or inspire dissent, all depending on the viewer’s perspective and personal experience. \n\nDefining Art Through Time\nArt, especially how we define it throughout history, has evolved across cultures, languages, and time periods. This evolution reflects cultural values, beliefs, and societal shifts impacting artistic definition, language, and interpretations. For example, the word "art" itself might seem ambiguous across different cultures as some may use alternative terms entirely for \'art\'.\n\n\nThe Sistine Chapel: A Symbol of Renaissance\nThis video delves into the history of Michelangelo\'s Sistine Chapel ceiling, exploring how such famous artworks intersect with larger historical context to inspire and guide art historians. \n\nEarly Influences In Art History\nPrevalent in ancient cultures like Plato and Aristotle\'s writings about the nature of reality, artists long recognized and engaged with art as a form of expression aimed at mimicking aspects of the real world. Notably, Zhang Yanyuan\'s work from the ninth century "Famous Paintings" serves as testament to this enduring fascination for the power and essence of art in ancient times \n\nThe Evolution of Art History\nArt historians have been working for centuries to decipher, categorize, and share information about various historical artworks through the years. From the Renaissance period\'s Vasari\'s book “Lives of the Most Excellent Italian Painters, Sculptors, and Architects” to contemporary scholars exploring the influence of art in society and culture—the craft of researching and studying these works continues to evolve with each generation. \n',
  'clean_text': 'Every piece of art tells a story. Usually, more than one. I\'ll show you. This is a biombo, a folding screen made in Mexico and inspired by Japanese decorative designs. It existed before we had pianos or bicycles or even sandwiches. This one would have decorated a wealthy Spaniard’s home in late seventeenth-century Mexico. And while it might look like mere decoration, if you lean in, it\'ll tell you a story. A story of a battle where Spain conquered Tenochtitlan, or modern-day Mexico City, and the Aztec emperor Moctezuma the Second was killed by one of his own subjects. But records from the Indigenous people of Mexico tell a different story of the same event. In their account, the Spanish killed the Aztec emperor as part of their conquest. Historical events like this—and history itself— aren\'t exactly straightforward. The story you get varies, depending on which documents or artworks you look at and who’s doing the telling. By studying this centuries-old screen, we learn about more than just the object itself. We learn about history—and how history, like art, is not something we discover but something we create. Hi! I’m Sarah Urist Green. I’m a curator and art educator, and this is Crash Course Art History. You might think that art history is a stuffy subject that\'s only useful for clinching a trivia night victory. Or you may think it\'s just memorizing a bunch of names and dates with the occasional jump-scare from a creepy, long-limbed baby. But art history is really about thinking critically by observing closely. It’s the study of objects and images to understand the people, places, and time periods they come from. Art reflects different perspectives and stories but also reveals the ideas that connect people across the world. And that three-letter word—"art"—holds some big ideas.  It can include ancient cave paintings and pride flags, state-funded monuments, and street art, works designed for function, and works designed to ruffle feathers.  And since art is subjective, what\'s a beautiful sculpture to one person might be the stuff of nightmares to another. Plus, ideas about what art is have changed—and continue to change—over time. Not all cultures think of art the same way, or even have a word for "art" in their language. Like, the Lega people from what’s now the Democratic Republic of the Congo have a category of objects called masengo, which roughly translates to “heavy things" and refers to items with great significance or "weight."  As for you, when you hear “art history,” you might think of something like this. Whoops, sorry, I meant, this: The well-known Sistine Chapel ceiling, painted by Michelangelo di Lodovico Buonarroti Simoni. No clue why we call him by his first name. But let\'s explore why that ceiling comes to mind when you think about art, and why you’ve heard of the guy who painted it. Let’s go to the drawing board! The story of the Sistine Chapel doesn\'t actually begin with Michelangelo, but with a wealthy Italian family called the Medicis. The Medicis ruled Florence and, later, Tuscany from the 15th to the 18th centuries. They also controlled the what, where, and how of local art scene. They financially supported several huge artists—including Michelangelo. So with the Medici Brand behind him, Michelangelo was basically one of Italy’s biggest influencers. He even caught the eye of Pope Julius II, who commissioned him to paint the now famous Sistine Chapel ceiling. Now, the Medicis were also sponsors of the painter and architect Giorgio Vasari, who wrote a book called “Lives of the Most Excellent Italian Painters, Sculptors, and Architects.” It celebrated Michelangelo and other artists like him, and it gave the Medicis credit for supporting a historical "rebirth." In fact, before the French term “Renaissance” became prominent in the 19th century, Vasari described this artistic moment in time as “rinascita”—Italian for “renewal” or “rebirth.”   So yeah, the book was basically 16th-century sponsored content, and it became the bedrock of what we know now as art history. It shaped not only how art history would be written but which artworks were considered important, talked about, and eventually meme-ified. Of course, writing about art didn\'t start with Vasari. By the fifth and fourth centuries B.C.E., Plato was wrestling with art’s imitation of reality in his writings, and Aristotle was exploring how art can conjure emotions. And in the ninth century, Zhang Yanyuan wrote "Famous Paintings of Successive  ... "\n \n',
  'keywords': 'creative process, art history, biographies, \nMexican art, biombo, Aztec, Spanish conquest, \nhistory, Indigenous accounts, perspective, interpretation, \nobjects and images,  humanities, \nart reflections, connections, ideas\nsubjectivity, cultural perspectives\ncontemporary art, historical events\nMichelangelo di Lodovico Buonarroti Simoni, Sistine Chapel, Renaissance, Vasari’s Lives of the Most Excellent Italian Painters, Giorgio Vasari, Medici family, Plato, Aristotle, Zhang Yanyuan. \n'})

### Generate Sample Queries

In [95]:
def find_symbol_positions(input_string):

    positions = {'[': [], ']': [], '"': [], "'": [], '-': [], '?': []}

    for symbol in positions.keys():
        # find all matches of the current symbol in the input string
        matches = [match.start() for match in re.finditer(re.escape(symbol), input_string)]
        positions[symbol] = matches

    return positions



def extract_query5_v2(input_string, positions, threshold=20):
    # threshold is just a failsafe against short quoted words
    if (len(positions['['])==0) or (len(positions[']'])==0):
        # if not within box brackets, queries might be between '-' and '?'
        quoted_strings = []
        j = 0
        for dash in positions['-']:
            while j < len(positions['?']) and positions['?'][j] <= dash:
                j+=1
            if j < len(positions['?']):
                if len(input_string[dash+1 : positions['?'][j]+1].replace('*','').strip()) > threshold:
                    quoted_strings.append(input_string[dash+1 : positions['?'][j]+1].replace('*','').strip())
        return quoted_strings
    
    quoted_strings = []

    for i in range(len(positions['['])):
        quoted_strings_tmp = []
        start_bracket = positions['['][i]
        end_bracket = next((pos for pos in positions[']'] if pos > start_bracket), None)

        if end_bracket is None:
            break
        
        quote_positions = [pos for pos in positions['"'] if start_bracket < pos < end_bracket]
        single_quotes = [pos for pos in positions["'"] if start_bracket < pos < end_bracket]

        print("DEBUG : quote_positions, single_quotes -- ", quote_positions, single_quotes)
        for i in range(0, len(quote_positions) - 1, 2):
            start_quote = quote_positions[i]
            end_quote = quote_positions[i + 1]
            for sq in single_quotes:
                if start_quote < sq < end_quote:
                    single_quotes.remove(sq)
            # extract the string between quotes and add it to the list
            if len(input_string[start_quote + 1:end_quote].replace('*','').strip()) > threshold:
                quoted_strings_tmp.append(input_string[start_quote + 1:end_quote].replace('*','').strip())
        
        if (quoted_strings_tmp==[]) and (len(positions['?']) > 0) and (len(single_quotes) > 0):
            # searching for queries be between "'" and '?'
            j = 0
            covered_pos = 0
            for squote in single_quotes:
                if covered_pos >= squote:
                    continue
                while j < len(positions['?']) and positions['?'][j] <= squote:
                    j+=1
                if j < len(positions['?']):
                    print("DEBUG: squote, j -- ",squote,j)
                    if len(input_string[squote+1 : positions['?'][j]+1].replace('*','').strip()) > threshold:
                        quoted_strings_tmp.append(input_string[squote+1 : positions['?'][j]+1].replace('*','').strip())
                        covered_pos = min([x for x in positions["'"] if x>positions['?'][j]]) # replaced 'single_quotes with positions["'"] to consider cases with "'" outside box bracket
                        # as add on case "'" could be before box bracket as well and this will lead to incorrect query getting captured
                        print("DEBUG: single_quotes, j, questionmark, covered_pos -- ", single_quotes, j, positions['?'][j], covered_pos)

        quoted_strings.extend(quoted_strings_tmp)

    return quoted_strings

In [ ]:
def find_symbol_positions(input_string):

    positions = {'[': [], ']': [], '"': [], "'": [], '-': [], '?': []}

    for symbol in positions.keys():
        # find all matches of the current symbol in the input string
        matches = [match.start() for match in re.finditer(re.escape(symbol), input_string)]
        positions[symbol] = matches

    return positions



def extract_query5_v3(input_string, positions, threshold=20):
    # threshold is just a failsafe against short quoted words
    if (len(positions['['])==0) or (len(positions[']'])==0):
        # if not within box brackets, queries might be between '-' and '?'
        quoted_strings = []
        j = 0
        for dash in positions['-']:
            while j < len(positions['?']) and positions['?'][j] <= dash:
                j+=1
            if j < len(positions['?']):
                if len(input_string[dash+1 : positions['?'][j]+1].replace('*','').strip()) > threshold:
                    quoted_strings.append(input_string[dash+1 : positions['?'][j]+1].replace('*','').strip())
        return quoted_strings
    
    quoted_strings = []

    for i in range(len(positions['['])):
        quoted_strings_tmp = []
        start_bracket = positions['['][i]
        end_bracket = next((pos for pos in positions[']'] if pos > start_bracket), None)

        if end_bracket is None:
            break
        
        double_quotes = [pos for pos in positions['"'] if start_bracket < pos < end_bracket]
        single_quotes = [pos for pos in positions["'"] if start_bracket < pos < end_bracket]
        all_quotes = sorted(double_quotes + single_quotes)

        print("DEBUG : double_quotes, single_quotes -- ", double_quotes, single_quotes)
        
        if (len(positions['?']) > 0) and (len(all_quotes) > 0):
            # searching for queries be between quotes and '?'
            j = 0
            covered_pos = 0
            for quote in all_quotes:
                if covered_pos >= quote:
                    continue
                while j < len(positions['?']) and positions['?'][j] <= quote:
                    j+=1
                if j < len(positions['?']):
                    print("DEBUG: quote, j -- ",quote,j)
                    if len(input_string[quote+1 : positions['?'][j]+1].replace('*','').strip()) > threshold:
                        quoted_strings_tmp.append(input_string[quote+1 : positions['?'][j]+1].replace('*','').strip())
                        covered_pos = min([x for x in positions["'"] if x>positions['?'][j]]) # replaced 'single_quotes with positions["'"] to consider cases with "'" outside box bracket
                        # as add on case "'" could be before box bracket as well and this will lead to incorrect query getting captured
                        print("DEBUG: single_quotes, j, questionmark, covered_pos -- ", single_quotes, j, positions['?'][j], covered_pos)

        quoted_strings.extend(quoted_strings_tmp)

    return quoted_strings

In [99]:
# sample queries for a single document/chunk
id=1
querydoc = generate_questions(documents[id], llm_model=LLM_MODEL)

print(f"Original Document: {documents[id]}\n\n")
print(f"Generated Queries: {querydoc}")

Original Document: {'uid': 't6Wc7OMks4U__B2__S61.88', 'text': " you look at, and who’s doing the telling. By studying this centuries-old screen we\xa0\nlearn about more than just the object itself. We learn about history — and how history,\xa0\xa0 like art, is not something we\xa0\ndiscover, but something we create. Hi! I'm Sarah Urist Green. I’m a curator and art educator, and\xa0\nthis is Crash Course Art History. You might think that art history\xa0\nis a stuffy subject that’s only\xa0\xa0 useful for clinching a trivia night victory. Or you might think it’s just\xa0\nmemorizing a bunch of names and dates,\xa0\xa0 with the occasional jump-scare\xa0\nfrom a creepy, long-limbed baby. But art history is really about thinking\xa0\ncritically by observing closely. It’s the study of objects and\xa0\nimages to understand the people,\xa0\xa0 places and time periods they come from. Art reflects different perspectives and stories\xa0\xa0 but also reveals the ideas that\xa0\nconnect people across the world. And that three-letter word —\xa0\n“art” — holds some big ideas. It can include ancient cave paintings and pride\xa0\nflags, state-funded monuments and street art,\xa0\xa0 works designed for function and\xa0\nworks designed to ruffle feathers. And since art is subjective, what’s\xa0\na beautiful sculpture to one person,\xa0\xa0 might be the stuff of nightmares to another. Plus, ideas about what art is have\xa0\nchanged—and continue to change—over time. Not all cultures think of art the same way, or\xa0\neven have a word for “art” in their language. Like, the Lega people from what’s now\xa0\nthe Democratic Republic of the Congo\xa0\xa0 have a category of objects called\xa0\nmasengo, which roughly translates\xa0\xa0 to “heavy things” and refers to items\xa0\nwith great significance or “weight.” As for you, when you hear “art history,”\xa0\nyou might think of something like this. Whoops, sorry, I meant, this: The\xa0\nwell-known Sistine Chapel ceiling,\xa0\xa0 painted by Michelangelo di\xa0\nLodovico Buonarroti Simoni. No clue why we call him by his first name. But let’s explore why that ceiling\xa0\ncomes to mind when you think about art,\xa0\xa0 and why you’ve heard of the guy who painted it. Let’s go to the drawing board! The story of the Sistine Chapel doesn’t\xa0\nactually begin with Michelangelo,\xa0\xa0 but with a wealthy Italian\xa0\nfamily called the Medicis. The Medicis ruled Florence and, later,\xa0\nTuscany, from the 15th to the 18th centuries. They also controlled the what, where,\xa0\nand how of the local art scene. They financially supported several\xa0\nhuge artists—including Michelangelo. So with the Medici Brand behind him, Michelangelo\xa0\nwas basically one of Italy’s biggest influencers. He even caught the eye of Pope Julius\xa0\nthe Second, who commissioned him to\xa0\xa0 paint the now famous Sistine Chapel ceiling. Now, the Medicis were also sponsors of the\xa0\npainter and architect Giorgio Vasari, who\xa0\xa0 wrote a book called “Lives of the Most Excellent\xa0\nItalian Painters, Sculptors, and Architects.” It celebrated Michelangelo\xa0\nand other artists like him,\xa0\xa0 and it gave the Medicis credit for\xa0\nsupporting a historic, quote, “rebirth.” In fact, before the French term “Renaissance”\xa0\nbecame prominent in the 19th century,\xa0\xa0 Vasari described this artistic moment in time as\xa0\n“rinascita”— Italian for “renewal” or “rebirth.” So yeah, the book was basically\xa0\nsixteenth-century sponsored content,\xa0\xa0 and it became the bedrock of\xa0\nwhat we know now as art history. It shaped not only the way\xa0\nart history would be written,\xa0\xa0 but which artworks were considered important,\xa0\ntalked about, and eventually meme-ified. Of course, writing about art\xa0\ndidn’t start with Vasari. By the fifth and fourth centuries B.C.E.,\xa0\nPlato was wrestling with art’s imitation\xa0\xa0 of reality in his writings, and Aristotle\xa0\nwas exploring how art can conjure emotions. And in the ninth century, Zhang Yanyuan\xa0\nwrote “Famous Paintings of Successive\xa0\xa0 Dynasties,” the oldest comprehensive written\xa0\nhistory of Chinese painting known to exist. So, there’s evidence of art historical\xa0\nwritings throughout the world,\xa0\xa0 and through much of recorded history. But Vasari’s series of biographies strongly\xa0\nshaped how the story of art would be told\xa0\xa0 from then on, with a significant\xa0\nbias toward Western European art. It was this text that became the basis of\xa0\nwhat is called the canon of art history:\xa0\xa0 a collection or timeline of artists and\xa0\nartworks believed to be truly great,\xa0\xa0 to have furthered art’s progress,\xa0\nthat get talked about again and again. So, yeah, who's in the canon and\xa0\nwho's out is pretty arbitrary! And because this is my series —\xa0\nand I don't think Vasari's gonna\xa0\xa0 mind — allow me to introduce.... my canon cannon. With its help, I, according to my own whims,\xa0\xa0 will launch people into my\xa0\npersonal canon of beloved artists. And you better watch out, Gauguin,\xa0\nI may also kick a few out, too.", 'smry_text': '### Crash Course Art History: Unveiling art\'s Past and Present\n\nThis introduction delves into the history of art through the lens of art history, exploring how objects tell stories. It aims to debunk popular misconceptions about the field. \n\n**The Purpose of Art History:** \n\nArt history transcends a dusty subject solely used for trivia nights.  Instead, it encourages critical observation and analysis, unveiling insights on historical context and people behind artworks.  Understanding different perspectives and narratives within art reveals underlying ideas across cultures and time periods. \n\n **Defining Art:** \nThe word "art" carries nuanced ideas, encompassing diverse expressions from ancient cave paintings to modern street art. Its subjective nature makes it a personal phenomenon, with each individual\'s interpretation shaping meaning. Additionally, the concept of what constitutes art has varied throughout time and cultures. Some may even question the existence of art, viewing any material representation as mere "heavy things" rather than a form of artistic expression. Examples provided are the Lega people\'s definition of "masengo," which refers to objects of deep significance.  This demonstrates how cultural contexts shape understanding. \n\n**Michelangelo and the Sistine Chapel:**\n The famous "Sistine Chapel Ceiling painted by Michelangelo di Lodovico Buonarroti Simoni" exemplifies a significant artistic era, shaped by the Medici family\'s substantial influence over Italian artistry. This impactful artwork fueled a Renaissance period, where art flourished under patronage:\n   * **Origins of Art History:**  Instead of an abrupt start in the 5th century B.C.E., art history started with Plato and Aristotle who examined imitation of reality through works like "Famous Paintings of Successive Dynasties" written as early as the 9th century C.E and later developed by historian Zhang Yanyuan, the oldest comprehensive record of Chinese painting history to exist.   \n* **The Legacy of Vasari:** \n Giorgio Vasari\'s extensive biographies contributed significantly to shaping what we call art history today: \n    * His biographical series cemented its framework: artists and artworks deemed "worthy" were showcased prominently, becoming the cornerstone for Western-centric interpretations. \n    * While this canon evolved through centuries, Vasari’s work created a template of art\'s development based on specific Western European examples.\n\n**Establishing Personal Artistic Canon:**\n The course invites viewers to challenge the established canon through Sarah Urist Green\'s own selection process, highlighting both historical figures and artworks that deeply resonate with her:\n\n\n* **The "Canon Cannon":**  This highlights different artistic periods and notable contributors across history to form a more balanced, personal overview.\n\n\n\nThrough these examples and discussions about art history, this course encourages a deeper understanding of its role in shaping our cultural perspective.\n', 'clean_text': '"You look at and who’s telling it. By studying this centuries-old screen we learn about more than just the object itself. We learn about history — and how history, like art, is not something we discover but something we create. Hi! I\'m Sarah Urist Green. I am a curator and art educator, and this is Crash Course Art History. You might think that art history is a stuffy subject that’s only useful for clinching a trivia night victory. Or you might think it’s just memorizing a bunch of names and dates, with the occasional jump-scare from a creepy, long-limbed baby. But art history is really about thinking critically by observing closely. It\'s the study of objects and images to understand the people, places, and time periods they come from. Art reflects different perspectives and stories but also reveals the ideas that connect people across the world. And that three-letter word — “art” — holds some big ideas. It can include ancient cave paintings and pride flags, state-funded monuments and street art, works designed for function and works designed to ruffle feathers. And since art is subjective, what’s a beautiful sculpture to one person might be the stuff of nightmares to another. Plus, ideas about what art is have changed — and continue to change — over time. Not all cultures think of art the same way or even have a word for “art” in their language. Like, the Lega people from what\'s now the Democratic Republic of the Congo have a category of objects called masengo, which roughly translates to "heavy things" and refers to items with great significance or weight.”  \n\nRegarding "art history,"  you might think of something like this. Whoops! Sorry, I mean this: The well-known Sistine Chapel ceiling, painted by Michelangelo di Lodovico Buonarroti Simoni. No clue why we call him by his first name. But let\'s explore why that ceiling comes to mind when you think about art, and why you’ve heard of the guy who painted it. Let’s go to the drawing board! The story of the Sistine Chapel doesn’t actually begin with Michelangelo, but with a wealthy Italian family called the Medicis. The Medicis ruled Florence and, later, Tuscany from the 15th to the 18th centuries. They also controlled what, where, and how of the local art scene. They financially supported several huge artists including Michelangelo. So, with the Medici Brand behind him, Michelangelo was basically one of Italy’s biggest influencers. He even caught the eye of Pope Julius the Second who commissioned him to paint the now famous Sistine Chapel ceiling. Now, the Medicis were also sponsors of the painter and architect Giorgio Vasari who wrote a book called "Lives of the Most Excellent Italian Painters, Sculptors, and Architects." It celebrated Michelangelo and other artists like him and gave the Medicis credit for supporting ‘a historic rebirth.\'  \nIn fact, before the French term "Renaissance" became prominent in the 19th century, Vasari described this artistic moment in time as “rinascita”—Italian for “renewal” or “rebirth.” So yeah, the book was basically sixteenth-century sponsored content and it became the bedrock of what we know now as art history. It shaped not only the way art history would be written, but which works were considered important, talked about, and eventually meme-ified. Of course, writing about art didn\'t start with Vasari. By the fifth and fourth centuries B.C.E., Plato was wrestling with art’s imitation of reality in his writings, and Aristotle was exploring how art can conjure emotions. And in the ninth century, Zhang Yanyuan wrote "Famous Paintings of Successive Dynasties," the oldest comprehensive written history of Chinese painting known to exist. So, there’s evidence of art historical writings throughout the world, and through much of recorded history. But Vasari\'s series of biographies strongly shaped how the story of art would be told from then on, with a significant bias toward Western European art. It was this text that became the basis of what is called the canon of art history: a collection or timeline of artists and works believed to be truly great, furthered art\'s progression, and get talked about again and again. So yeah, who’s in the canon and who’s out is pretty arbitrary! And because this is my series — and I don’t think Vasari\'s going to mind — allow me to introduce...my canon cannon. With its help, I, according to my own whims, will launch people into my personal canon of beloved artists.  And you better watch out, Gauguin, I may also kick a few out, too. \n', 'keywords': "sart history, art appreciation, object studying, visual arts, art as expression, history and art connection, time periods, cultures and art, perspective on art, subjective perception of art, Western Art, Michelangelo di Lodovico Buonarroti Simoni, Sistine Chapel ceiling, Renaissance art movement, Medici family, art patronage, Giorgio Vasari, Lives of the Most Excellent Italian Painters, Sculptors, and Architects, Rennaissance art, Plato's philosophy, Aristotle's theory of art, Chinese painting, historical art criticism, canon of art history, artists' biography, art history bias. \n"}


Generated Queries:  [
    "What are the fundamental approaches to studying art and how does it help us understand the objects and images we encounter?",
    "How has the definition of art evolved throughout history and which cultural perspectives stand out in understanding different art forms?",
    "Why is the story behind the Sistine Chapel ceiling so crucial in understanding the role of artists, patrons, and the shift towards Renaissance thought during this artistic era?",
    "Who were some historical figures who shaped our current understanding of art through their writings on art history, like Plato, Aristotle, or Vasari? How has the history affected Western art as a whole?",
     "How do we recognize artists and works that are considered to be classics in art history? What is the role and importance of a "canon of art history?"  Give an example of why some artistic traditions are left out of the canon".


 ]

In [100]:
# original llm response
querydoc

' [\n    "What are the fundamental approaches to studying art and how does it help us understand the objects and images we encounter?",\n    "How has the definition of art evolved throughout history and which cultural perspectives stand out in understanding different art forms?", \n    "Why is the story behind the Sistine Chapel ceiling so crucial in understanding the role of artists, patrons, and the shift towards Renaissance thought during this artistic era?", \n    "Who were some historical figures who shaped our current understanding of art through their writings on art history, like Plato, Aristotle, or Vasari? How has the history affected Western art as a whole?",\n     "How do we recognize artists and works that are considered to be classics in art history? What is the role and importance of a "canon of art history?"  Give an example of why some artistic traditions are left out of the canon". \n\n\n ]'

In [103]:
positions = find_symbol_positions(querydoc)
positions

{'[': [1],
 ']': [911],
 '"': [7, 131, 138, 275, 283, 460, 468, 671, 679, 806, 828, 904],
 "'": [],
 '-': [],
 '?': [130, 274, 459, 617, 670, 767, 827]}

In [102]:
extract_query5_v2(querydoc, positions)

DEBUG : quote_positions, single_quotes --  [7, 131, 138, 275, 283, 460, 468, 671, 679, 806, 828, 904] []

['What are the fundamental approaches to studying art and how does it help us understand the objects and images we encounter?',
 'How has the definition of art evolved throughout history and which cultural perspectives stand out in understanding different art forms?',
 'Why is the story behind the Sistine Chapel ceiling so crucial in understanding the role of artists, patrons, and the shift towards Renaissance thought during this artistic era?',
 'Who were some historical figures who shaped our current understanding of art through their writings on art history, like Plato, Aristotle, or Vasari? How has the history affected Western art as a whole?',
 'How do we recognize artists and works that are considered to be classics in art history? What is the role and importance of a',
 'Give an example of why some artistic traditions are left out of the canon']

### Generating Ground Truth File

In [117]:
df_query5 = generate_query_file(documents[:3], llm_model='gemma2:2b', retry=3)
df_query5.shape, df_query5.head(20)

INFO: initiated query generation
INFO: total text chunks 3

Generating Queries:   0%|          | 0/3 [00:00<?, ?it/s]

INFO: query generation finished
INFO: total documents - 3 | success - 2 | failure - 1

                        uid                                              query
0   t6Wc7OMks4U__B2__S61.88                       What exactly is art history?
1   t6Wc7OMks4U__B2__S61.88        How has the study of art changed over time?
2   t6Wc7OMks4U__B2__S61.88               How important is historical context?
3   t6Wc7OMks4U__B2__S61.88  Who decides which works of art should count to...
4   t6Wc7OMks4U__B2__S61.88  What are some modern examples of how the canon...
5  t6Wc7OMks4U__B3__S121.84  economic upheaval, or personal/artistic prefer...
6  t6Wc7OMks4U__B3__S121.84                               How Do We Define It?

In [ ]:
# create the directory if it doesn't exist
os.makedirs("../data/ground_truth/", exist_ok=True)

export_df_to_json(df_query5, "../data/ground_truth/ground_truth_retrieval.json")